apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: todoapp
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: todoapp
data:
  DOTNET_ENVIRONMENT: "Production"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Username: "guest"
  Serilog__MinimumLevel__Default: "Information"
  Serilog__MinimumLevel__Override__Microsoft: "Warning"
  Serilog__MinimumLevel__Override__System: "Warning"
