apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todoapp
  labels:
    app.kubernetes.io/name: todo-service
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: todo-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
